import * as vscode from 'vscode';
import * as path from 'path';
import { Note, Tag, NOTE_COLORS } from './NoteStorage';

// ─── Public entry point ───────────────────────────────────────────────────────

/**
 * Shows a format picker then exports the given notes as a Markdown file,
 * HTML file, or clipboard copy.
 */
export async function runExport(notes: Note[], tags: Tag[]): Promise<void> {
  if (notes.length === 0) {
    vscode.window.showInformationMessage('DevNotes: nothing to export.');
    return;
  }

  type FmtItem = vscode.QuickPickItem & { fmt: 'markdown' | 'html' | 'clipboard' };
  const items: FmtItem[] = [
    {
      label      : '$(markdown) Markdown file',
      description: '.md — readable in any editor or wiki',
      fmt        : 'markdown',
    },
    {
      label      : '$(globe) HTML file',
      description: '.html — styled, shareable with non-developers',
      fmt        : 'html',
    },
    {
      label      : '$(clippy) Copy to clipboard',
      description: 'Markdown — paste into Slack, Notion, GitHub…',
      fmt        : 'clipboard',
    },
  ];

  const picked = await vscode.window.showQuickPick(items, {
    placeHolder: `Export ${notes.length} note${notes.length > 1 ? 's' : ''} as…`,
  });
  if (!picked) return;

  const content = picked.fmt === 'html'
    ? toHtml(notes, tags)
    : toMarkdown(notes, tags);

  // ── Clipboard ──────────────────────────────────────────────────────────
  if (picked.fmt === 'clipboard') {
    await vscode.env.clipboard.writeText(content);
    vscode.window.showInformationMessage(
      `Copied ${notes.length} note${notes.length > 1 ? 's' : ''} to clipboard.`
    );
    return;
  }

  // ── Save to file ───────────────────────────────────────────────────────
  const ext      = picked.fmt === 'html' ? 'html' : 'md';
  const baseName = notes.length === 1
    ? notes[0].title.replace(/[^a-z0-9]+/gi, '-').toLowerCase().slice(0, 60)
    : 'devnotes-export';

  const uri = await vscode.window.showSaveDialog({
    defaultUri: vscode.Uri.file(`${baseName}.${ext}`),
    filters    : picked.fmt === 'html'
      ? { 'HTML Files': ['html'] }
      : { 'Markdown Files': ['md'] },
  });
  if (!uri) return;

  await vscode.workspace.fs.writeFile(uri, new TextEncoder().encode(content));

  const action = await vscode.window.showInformationMessage(
    `Exported ${notes.length} note${notes.length > 1 ? 's' : ''} to ${path.basename(uri.fsPath)}`,
    'Open file'
  );
  if (action === 'Open file') {
    vscode.commands.executeCommand('vscode.open', uri);
  }
}

// ─── Markdown formatter ───────────────────────────────────────────────────────

function toMarkdown(notes: Note[], tags: Tag[]): string {
  const lines: string[] = [];
  const now = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

  if (notes.length > 1) {
    lines.push(`# DevNotes Export`, ``, `*${notes.length} notes exported on ${now}*`, ``);
  }

  for (const note of notes) {
    lines.push(`# ${note.title}`, ``);
    if (note.content.trim()) lines.push(note.content.trim(), ``);

    const meta: string[] = [];
    if (note.tags.length > 0) {
      meta.push(`**Tags:** ${note.tags.map(id => tagLabel(id, tags)).join(', ')}`);
    }
    if (note.branch)   meta.push(`**Branch:** ${note.branch}`);
    if (note.remindAt) meta.push(`**Reminder:** ${formatDate(note.remindAt)}`);
    meta.push(`**Created:** ${formatDate(note.createdAt)}`);
    meta.push(`**Updated:** ${formatDate(note.updatedAt)}`);

    lines.push(meta.join('  \n'), ``, `---`, ``);
  }

  if (notes.length > 1) {
    lines.push(`*Generated by DevNotes*`);
  }

  return lines.join('\n');
}

// ─── HTML formatter ───────────────────────────────────────────────────────────

function toHtml(notes: Note[], tags: Tag[]): string {
  const now  = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });
  const body = notes.map(n => noteToHtml(n, tags)).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>DevNotes Export</title>
<style>
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f8f9fa;color:#1a1a2e;padding:40px 20px;line-height:1.7}
  .container{max-width:780px;margin:0 auto}
  .header{margin-bottom:32px;padding-bottom:20px;border-bottom:2px solid #e2e8f0}
  .header h1{font-size:1.6em;font-weight:800;margin-bottom:6px}
  .header p{font-size:13px;color:#64748b}
  .note{background:#fff;border-radius:12px;padding:28px;margin-bottom:24px;box-shadow:0 1px 4px rgba(0,0,0,.07)}
  .note-title{font-size:1.3em;font-weight:700;margin-bottom:16px}
  .note-body h1,.note-body h2,.note-body h3{font-weight:700;margin:1em 0 .4em;line-height:1.3}
  .note-body h1{font-size:1.4em}.note-body h2{font-size:1.2em}.note-body h3{font-size:1.05em}
  .note-body p{margin-bottom:.7em}
  .note-body ul,.note-body ol{padding-left:1.5em;margin-bottom:.7em}
  .note-body li{margin:2px 0}
  .note-body code{background:#f1f5f9;padding:1px 5px;border-radius:3px;font-family:monospace;font-size:.875em}
  .note-body pre{background:#f1f5f9;padding:14px 18px;border-radius:8px;overflow-x:auto;margin-bottom:.7em}
  .note-body pre code{background:none;padding:0}
  .note-body blockquote{border-left:3px solid #cbd5e1;margin:.7em 0;padding-left:1em;color:#64748b}
  .note-body input[type=checkbox]{margin-right:6px}
  .note-meta{margin-top:20px;padding-top:14px;border-top:1px solid #e2e8f0;font-size:12px;color:#64748b;display:flex;flex-wrap:wrap;gap:10px}
  .tag{display:inline-block;padding:1px 8px;border-radius:10px;font-size:11px;font-weight:600;color:#1a1a2e;margin-right:3px}
  .footer{text-align:center;font-size:12px;color:#94a3b8;margin-top:40px}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>DevNotes Export</h1>
    <p>${notes.length} note${notes.length > 1 ? 's' : ''} &mdash; ${esc(now)}</p>
  </div>
  ${body}
  <div class="footer">Generated by DevNotes</div>
</div>
</body>
</html>`;
}

function noteToHtml(note: Note, tags: Tag[]): string {
  const color  = NOTE_COLORS[note.color] ?? NOTE_COLORS.yellow;
  const tagPills = note.tags
    .map(id => {
      const t = tags.find(t => t.id === id);
      return t ? `<span class="tag" style="background:${esc(t.color)}">${esc(t.label)}</span>` : '';
    })
    .join('');

  const metaParts: string[] = [];
  if (tagPills) metaParts.push(`<span>Tags: ${tagPills}</span>`);
  if (note.branch) metaParts.push(`<span>Branch: ${esc(note.branch)}</span>`);
  if (note.codeLink) metaParts.push(`<span>Linked: ${esc(note.codeLink.file)}:${note.codeLink.line}</span>`);
  if (note.remindAt) metaParts.push(`<span>Reminder: ${esc(formatDate(note.remindAt))}</span>`);
  metaParts.push(`<span>Created: ${esc(formatDate(note.createdAt))}</span>`);
  metaParts.push(`<span>Updated: ${esc(formatDate(note.updatedAt))}</span>`);

  return `<div class="note" style="border-left:4px solid ${color}">
  <div class="note-title">${esc(note.title)}</div>
  <div class="note-body">${mdToHtml(note.content)}</div>
  <div class="note-meta">${metaParts.join('\n  ')}</div>
</div>`;
}

// ─── Markdown → HTML (basic converter for export) ─────────────────────────────

function mdToHtml(md: string): string {
  if (!md.trim()) return '';
  const lines  = md.split('\n');
  let   out    = '';
  let   inList = false;
  let   inCode = false;
  let   codeAccum = '';

  const closeList = (): void => {
    if (inList) { out += '</ul>\n'; inList = false; }
  };

  const inline = (s: string): string =>
    esc(s)
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g,     '<em>$1</em>')
      .replace(/`(.+?)`/g,       '<code>$1</code>')
      .replace(/~~(.+?)~~/g,     '<del>$1</del>');

  for (const line of lines) {
    if (line.startsWith('```')) {
      if (inCode) {
        out += `<pre><code>${esc(codeAccum.replace(/\n$/, ''))}</code></pre>\n`;
        codeAccum = ''; inCode = false;
      } else {
        closeList(); inCode = true;
      }
      continue;
    }
    if (inCode) { codeAccum += line + '\n'; continue; }

    const h = line.match(/^(#{1,3})\s+(.*)/);
    if (h) {
      closeList();
      out += `<h${h[1].length}>${inline(h[2])}</h${h[1].length}>\n`;
      continue;
    }

    const task = line.match(/^- \[([ x])\] (.*)/);
    if (task) {
      if (!inList) { out += '<ul style="list-style:none;padding-left:0">\n'; inList = true; }
      out += `<li><input type="checkbox"${task[1] === 'x' ? ' checked' : ''} disabled> ${inline(task[2])}</li>\n`;
      continue;
    }

    const li = line.match(/^[-*] (.*)/);
    if (li) {
      if (!inList) { out += '<ul>\n'; inList = true; }
      out += `<li>${inline(li[1])}</li>\n`;
      continue;
    }

    const bq = line.match(/^> (.*)/);
    if (bq) {
      closeList();
      out += `<blockquote>${inline(bq[1])}</blockquote>\n`;
      continue;
    }

    closeList();
    if (line.trim() === '') { out += '<br>\n'; continue; }
    out += `<p>${inline(line)}</p>\n`;
  }
  closeList();
  return out;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function tagLabel(id: string, tags: Tag[]): string {
  return tags.find(t => t.id === id)?.label ?? id;
}

function formatDate(ts: number): string {
  return new Date(ts).toLocaleDateString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric',
  });
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
